# SPDX-License-Identifier: Cartulary-Sustainable-Use-1.0

defmodule Cartulary.Portability.Archive do
  @moduledoc """
  F10 versioned logical Account archive.

  The archive is a gzip-compressed tar containing a manifest, one JSONL file
  per durable resource, and checksum-addressed raw blobs. Export is read from
  one Account-scoped database transaction. Import validates the complete
  archive and audit chain before its single Ash transaction begins.
  """

  alias Cartulary.Actor
  alias Cartulary.DataLayer
  alias Cartulary.Documents.BlobStore
  alias Cartulary.Governance.AuditEvent
  alias Cartulary.Observations.DocumentVersion
  alias Cartulary.Operations.PipelineRun
  alias Cartulary.Pipeline.Idempotency
  alias Cartulary.Portability.AuditVerifier
  alias Cartulary.Portability.Registry

  require Ash.Query

  @schema "cartulary-account-1"

  # The only caller-controlled path is an operator CLI destination; archive
  # contents are written under a generated private temporary root.
  # sobelow_skip ["Traversal.FileModule"]
  def export(%Actor{} = actor, output_path) when is_binary(output_path) do
    started_at = System.monotonic_time()
    root = temp_dir!("cartulary-export")

    try do
      {manifest, manifest_bytes} =
        DataLayer.with_actor(actor, fn account, current_actor ->
          write_export!(root, account, current_actor)
        end)

      File.write!(Path.join(root, "manifest.json"), manifest_bytes, [:binary])
      create_tar!(root, output_path)

      duration_ms = duration_ms(started_at)

      :telemetry.execute(
        [:cartulary, :portability, :export],
        %{duration: duration_ms, resources: length(manifest["resources"])},
        %{status: :ok}
      )

      {:ok,
       %{
         path: Path.expand(output_path),
         schema: @schema,
         account_id: manifest["account"]["id"],
         resource_counts: Map.new(manifest["resources"], &{&1["name"], &1["count"]}),
         blob_count: length(manifest["blobs"]),
         audit: manifest["audit"],
         duration_ms: duration_ms
       }}
    after
      File.rm_rf!(root)
    end
  end

  def import(input_path) when is_binary(input_path) do
    started_at = System.monotonic_time()
    root = temp_dir!("cartulary-import")

    try do
      extract_tar!(input_path, root)
      {manifest, rows, blob_bytes, manifest_hash} = validate_archive!(root)
      account = Map.fetch!(manifest, "account")
      account_id = Map.fetch!(account, "id")
      account_key = Map.fetch!(account, "key")
      target_blob_refs = store_blobs!(account_id, blob_bytes)

      result =
        DataLayer.with_portability_import(account_id, account_key, fn actor ->
          ensure_fresh_target!(actor)
          imported = import_rows!(rows, target_blob_refs, actor)
          enqueue_rebuilds!(rows, manifest_hash, actor)
          imported
        end)

      duration_ms = duration_ms(started_at)

      :telemetry.execute(
        [:cartulary, :portability, :import],
        %{duration: duration_ms, resources: map_size(rows)},
        %{status: :ok}
      )

      {:ok,
       Map.merge(result, %{
         schema: @schema,
         account_id: account_id,
         manifest_hash: manifest_hash,
         audit: manifest["audit"],
         duration_ms: duration_ms
       })}
    after
      File.rm_rf!(root)
    end
  end

  def validate(input_path) when is_binary(input_path) do
    root = temp_dir!("cartulary-validate")

    try do
      extract_tar!(input_path, root)
      {manifest, _rows, _blobs, manifest_hash} = validate_archive!(root)

      {:ok,
       %{
         schema: manifest["schema"],
         account_id: manifest["account"]["id"],
         manifest_hash: manifest_hash,
         audit: manifest["audit"]
       }}
    after
      File.rm_rf!(root)
    end
  end

  # `root` is generated by `temp_dir!/1`; resource names come from Registry.
  # sobelow_skip ["Traversal.FileModule"]
  defp write_export!(root, account, actor) do
    resources_dir = Path.join(root, "resources")
    blobs_dir = Path.join(root, "blobs")
    File.mkdir_p!(resources_dir)
    File.mkdir_p!(blobs_dir)

    {resource_entries, exported_rows} =
      Enum.map_reduce(Registry.resources(), %{}, fn {name, resource}, rows_by_name ->
        rows = read_rows(resource, account.id, actor)
        path = Path.join(resources_dir, "#{name}.jsonl")
        bytes = encode_jsonl(rows)
        File.write!(path, bytes, [:binary])

        entry = %{
          "name" => name,
          "file" => "resources/#{name}.jsonl",
          "count" => length(rows),
          "sha256" => sha256(bytes)
        }

        {entry, Map.put(rows_by_name, name, rows)}
      end)

    blobs =
      exported_rows
      |> Map.fetch!("document_versions")
      |> write_blobs!(blobs_dir)

    {:ok, audit} =
      exported_rows
      |> Map.fetch!("audit_events")
      |> AuditVerifier.verify()

    embedder =
      :embedder |> Cartulary.Model.Config.resolve(%{}) |> Cartulary.Model.Config.provenance()

    manifest = %{
      "schema" => @schema,
      "created_at" => DateTime.utc_now() |> DateTime.to_iso8601(),
      "account" => %{"id" => account.id, "key" => account.key, "name" => account.name},
      "embedder" => stringify_map(embedder),
      "resources" => resource_entries,
      "blobs" => blobs,
      "audit" => stringify_map(audit),
      "excluded" => %{
        "derived_resources" => Enum.map(Registry.derived_resources(), &resource_name/1),
        "credential_resources" => Enum.map(Registry.credential_resources(), &resource_name/1),
        "vectors" => "rebuild_on_import",
        "secrets" => "never_exported"
      }
    }

    manifest_bytes = Jason.encode!(manifest, pretty: true)
    {manifest, manifest_bytes}
  end

  defp read_rows(resource, account_id, actor) do
    query =
      if resource == Cartulary.Accounts.Account do
        Ash.Query.filter(resource, id == ^account_id)
      else
        Ash.Query.filter(resource, account_id == ^account_id)
      end

    query =
      query
      |> Ash.Query.for_read(:portability_export)
      |> Ash.Query.sort(id: :asc)
      |> maybe_set_tenant(resource, account_id)

    query
    |> Ash.stream!(actor: actor, batch_size: 500, stream_with: :keyset)
    |> Enum.to_list()
    |> Enum.map(&serialize_record(resource, &1))
    |> sort_for_import(resource)
  end

  defp maybe_set_tenant(query, Cartulary.Accounts.Account, _account_id), do: query
  defp maybe_set_tenant(query, _resource, account_id), do: Ash.Query.set_tenant(query, account_id)

  defp serialize_record(resource, record) do
    excluded = Registry.excluded_attributes(resource)

    resource
    |> Ash.Resource.Info.attributes()
    |> Enum.reject(&(&1.name in excluded))
    |> Map.new(fn attribute ->
      {Atom.to_string(attribute.name), Map.get(record, attribute.name)}
    end)
  end

  defp sort_for_import(rows, Cartulary.Topology.Scope),
    do: Enum.sort_by(rows, &{Map.fetch!(&1, "path"), Map.fetch!(&1, "id")})

  defp sort_for_import(rows, Cartulary.Knowledge.KnowledgeItem),
    do: sort_supersession_rows(rows, MapSet.new(), [])

  defp sort_for_import(rows, AuditEvent),
    do: Enum.sort_by(rows, &{Map.fetch!(&1, "inserted_at"), Map.fetch!(&1, "id")})

  defp sort_for_import(rows, _resource), do: rows

  defp sort_supersession_rows([], _seen, result), do: Enum.reverse(result)

  defp sort_supersession_rows(rows, seen, result) do
    {ready, pending} =
      Enum.split_with(rows, fn row ->
        supersedes_id = row["supersedes_id"]
        is_nil(supersedes_id) or MapSet.member?(seen, supersedes_id)
      end)

    if ready == [] do
      raise "knowledge supersession graph is cyclic or references a missing item"
    end

    ready = Enum.sort_by(ready, &{Map.fetch!(&1, "inserted_at"), Map.fetch!(&1, "id")})
    seen = Enum.reduce(ready, seen, &MapSet.put(&2, Map.fetch!(&1, "id")))
    sort_supersession_rows(pending, seen, Enum.reverse(ready, result))
  end

  # Blob filenames are verified lowercase SHA-256 content hashes.
  # sobelow_skip ["Traversal.FileModule"]
  defp write_blobs!(version_rows, blobs_dir) do
    version_rows
    |> Enum.uniq_by(&Map.fetch!(&1, "content_hash"))
    |> Enum.map(fn row ->
      hash = Map.fetch!(row, "content_hash")

      bytes =
        case BlobStore.get(Map.fetch!(row, "blob_ref")) do
          {:ok, bytes} -> bytes
          {:error, :legacy_blob_requires_version_content} -> Map.fetch!(row, "content")
          {:error, reason} -> raise "cannot export blob #{hash}: #{inspect(reason)}"
        end

      if Idempotency.content_hash(bytes) != hash do
        raise "document blob checksum mismatch for #{hash}"
      end

      File.write!(Path.join(blobs_dir, hash), bytes, [:binary])

      %{
        "content_hash" => hash,
        "file" => "blobs/#{hash}",
        "byte_size" => byte_size(bytes),
        "sha256" => sha256(bytes)
      }
    end)
    |> Enum.sort_by(& &1["content_hash"])
  end

  # `root` is generated locally and archive entries pass `safe_join!/2`.
  # sobelow_skip ["Traversal.FileModule"]
  defp validate_archive!(root) do
    manifest_path = safe_join!(root, "manifest.json")
    manifest_bytes = File.read!(manifest_path)
    manifest = Jason.decode!(manifest_bytes)

    unless manifest["schema"] == @schema do
      raise "unsupported portability schema: #{inspect(manifest["schema"])}"
    end

    rows =
      Map.new(manifest["resources"], fn entry ->
        name = Map.fetch!(entry, "name")
        Registry.resource!(name)
        bytes = read_verified!(root, entry)
        decoded = decode_jsonl(bytes)

        if length(decoded) != Map.fetch!(entry, "count") do
          raise "resource count mismatch for #{name}"
        end

        {name, decoded}
      end)

    audit_rows = Map.fetch!(rows, "audit_events")

    case AuditVerifier.verify(audit_rows) do
      {:ok, actual} ->
        expected = manifest["audit"]

        unless actual.count == expected["count"] and actual.last_hash == expected["last_hash"] do
          raise "audit manifest does not match the verified chain"
        end

      {:error, reason} ->
        raise "audit chain verification failed: #{inspect(reason)}"
    end

    blobs =
      Map.new(manifest["blobs"], fn entry ->
        bytes = read_verified!(root, entry)
        hash = Map.fetch!(entry, "content_hash")

        unless byte_size(bytes) == Map.fetch!(entry, "byte_size") and
                 Idempotency.content_hash(bytes) == hash do
          raise "blob content verification failed for #{hash}"
        end

        {hash, bytes}
      end)

    {manifest, rows, blobs, sha256(manifest_bytes)}
  end

  # `safe_join!/2` proves the manifest path stays inside the extraction root.
  # sobelow_skip ["Traversal.FileModule"]
  defp read_verified!(root, entry) do
    file = Map.fetch!(entry, "file")
    bytes = root |> safe_join!(file) |> File.read!()

    unless sha256(bytes) == Map.fetch!(entry, "sha256") do
      raise "archive checksum mismatch for #{file}"
    end

    bytes
  end

  defp store_blobs!(account_id, blob_bytes) do
    Map.new(blob_bytes, fn {hash, bytes} ->
      case BlobStore.put(account_id, hash, bytes) do
        {:ok, blob_ref} -> {hash, blob_ref}
        {:error, reason} -> raise "cannot import blob #{hash}: #{inspect(reason)}"
      end
    end)
  end

  defp ensure_fresh_target!(actor) do
    existing =
      Cartulary.Accounts.Account
      |> Ash.Query.filter(id == ^actor.account_id)
      |> Ash.read_one!(actor: actor)

    if existing, do: raise("portability import requires a fresh target Account")
  end

  defp import_rows!(rows, target_blob_refs, actor) do
    counts =
      Enum.map(Registry.resources(), fn {name, resource} ->
        imported =
          rows
          |> Map.fetch!(name)
          |> Enum.map(&rewrite_blob_ref(resource, &1, target_blob_refs))
          |> Enum.map(&import_record!(resource, &1, actor))

        {name, length(imported)}
      end)

    restore_deferred_links!(rows, actor)
    %{resource_counts: Map.new(counts), blob_count: map_size(target_blob_refs)}
  end

  defp rewrite_blob_ref(DocumentVersion, row, target_blob_refs) do
    Map.put(row, "blob_ref", Map.fetch!(target_blob_refs, Map.fetch!(row, "content_hash")))
  end

  defp rewrite_blob_ref(_resource, row, _target_blob_refs), do: row

  defp import_record!(resource, attributes, actor) do
    attributes = drop_deferred_attributes(resource, attributes)

    changeset =
      resource
      |> Ash.Changeset.new()
      |> maybe_set_changeset_tenant(resource, actor.account_id)
      |> Ash.Changeset.for_create(:portability_import, %{attributes: attributes})

    Ash.create!(changeset, actor: actor)
  end

  defp drop_deferred_attributes(Cartulary.Observations.Document, attributes),
    do: Map.drop(attributes, ["current_version_id"])

  defp drop_deferred_attributes(_resource, attributes), do: attributes

  defp restore_deferred_links!(rows, actor) do
    Enum.each(Map.fetch!(rows, "documents"), fn row ->
      if current_version_id = row["current_version_id"] do
        document =
          Cartulary.Observations.Document
          |> Ash.Query.filter(id == ^Map.fetch!(row, "id"))
          |> Ash.Query.set_tenant(actor.account_id)
          |> Ash.read_one!(actor: actor)

        document
        |> Ash.Changeset.for_update(:portability_restore, %{
          attributes: %{"current_version_id" => current_version_id}
        })
        |> Ash.update!(actor: actor)
      end
    end)
  end

  defp maybe_set_changeset_tenant(changeset, Cartulary.Accounts.Account, _account_id),
    do: changeset

  defp maybe_set_changeset_tenant(changeset, _resource, account_id),
    do: Ash.Changeset.set_tenant(changeset, account_id)

  defp enqueue_rebuilds!(rows, manifest_hash, actor) do
    scope_ids = Enum.map(Map.fetch!(rows, "scopes"), &Map.fetch!(&1, "id"))
    version_ids = Enum.map(Map.fetch!(rows, "document_versions"), &Map.fetch!(&1, "id"))

    Enum.each(scope_ids, fn scope_id ->
      enqueue_rebuild!(actor, "scope", scope_id, manifest_hash)
    end)

    Enum.each(version_ids, fn version_id ->
      enqueue_rebuild!(actor, "document_version", version_id, manifest_hash)
    end)
  end

  defp enqueue_rebuild!(actor, target_type, target_id, manifest_hash) do
    import_id = "#{target_type}:#{target_id}"

    PipelineRun
    |> Ash.Changeset.new()
    |> Ash.Changeset.set_tenant(actor.account_id)
    |> Ash.Changeset.for_create(:enqueue_import_rebuild, %{
      target_type: target_type,
      target_id: target_id,
      idempotency_key: Idempotency.import_rebuild(import_id, manifest_hash),
      payload: %{"manifest_hash" => manifest_hash}
    })
    |> Ash.create!(actor: actor)
  end

  defp encode_jsonl([]), do: ""

  defp encode_jsonl(rows) do
    Enum.map_join(rows, "", fn row -> Jason.encode!(row) <> "\n" end)
  end

  defp decode_jsonl(""), do: []

  defp decode_jsonl(bytes) do
    bytes
    |> String.split("\n", trim: true)
    |> Enum.map(&Jason.decode!/1)
  end

  # Output is an operator CLI path; inputs remain inside the generated root.
  # sobelow_skip ["Traversal.FileModule"]
  defp create_tar!(root, output_path) do
    output = Path.expand(output_path)
    File.mkdir_p!(Path.dirname(output))
    temp_output = output <> ".tmp-" <> Integer.to_string(System.unique_integer([:positive]))

    {:ok, tar} = :erl_tar.open(String.to_charlist(temp_output), [:write, :compressed])

    result =
      root
      |> Path.join("**/*")
      |> Path.wildcard(match_dot: true)
      |> Enum.filter(&File.regular?/1)
      |> Enum.reduce_while(:ok, fn path, :ok ->
        relative = Path.relative_to(path, root)

        case :erl_tar.add(tar, String.to_charlist(path), String.to_charlist(relative), []) do
          :ok -> {:cont, :ok}
          {:error, reason} -> {:halt, {:error, reason}}
        end
      end)

    :ok = :erl_tar.close(tar)

    case result do
      :ok -> File.rename!(temp_output, output)
      {:error, reason} -> raise "cannot create portability archive: #{inspect(reason)}"
    end
  end

  defp extract_tar!(input_path, root) do
    archive = String.to_charlist(Path.expand(input_path))

    entries =
      case :erl_tar.table(archive, [:compressed]) do
        {:ok, names} -> names
        {:error, reason} -> raise "cannot inspect portability archive: #{inspect(reason)}"
      end

    Enum.each(entries, fn name ->
      name = List.to_string(name)

      if Path.type(name) == :absolute or ".." in Path.split(name) do
        raise "unsafe path in portability archive"
      end
    end)

    case :erl_tar.extract(archive, [:compressed, cwd: String.to_charlist(root)]) do
      :ok -> :ok
      {:error, reason} -> raise "cannot extract portability archive: #{inspect(reason)}"
    end
  end

  defp safe_join!(root, relative) do
    expanded_root = Path.expand(root)
    expanded = Path.expand(relative, expanded_root)

    unless expanded == expanded_root or String.starts_with?(expanded, expanded_root <> "/") do
      raise "archive path escapes extraction root"
    end

    expanded
  end

  # Prefixes are module constants and the parent comes from the system runtime.
  # sobelow_skip ["Traversal.FileModule"]
  defp temp_dir!(prefix) do
    path =
      Path.join(
        System.tmp_dir!(),
        "#{prefix}-#{System.unique_integer([:positive, :monotonic])}"
      )

    File.mkdir_p!(path)
    path
  end

  defp resource_name(resource), do: resource |> Module.split() |> Enum.join(".")

  defp stringify_map(map), do: Map.new(map, fn {key, value} -> {to_string(key), value} end)

  defp sha256(bytes),
    do: :crypto.hash(:sha256, bytes) |> Base.encode16(case: :lower)

  defp duration_ms(started_at),
    do: System.convert_time_unit(System.monotonic_time() - started_at, :native, :millisecond)
end
